### ISSUE TITLE
Déploiement Tomcat - java.lang.NoClassDefFoundError: com/github/jaiimageio/stream/RawImageInputStream

### ISSUE THREAD

**Issue by fbordina** [EsupPortail/esup-signature#10]
Bonjour,

nous déployons la version 1.3 de l'application sous Tomcat/ROOT comme proposé dans la [documentation](https://www.esup-portail.org/wiki/pages/viewpage.action?pageId=818708487) (Debian 10, Tomcat 9,  openjdk 13). Nous rencontrons des erreurs 500 à chaque action impliquant des fichiers. La trace est ci-dessous. Après quelques recherches, l'origine du problème est peut-être [là :](https://github.com/haraldk/TwelveMonkeys#deploying-the-plugins-in-a-web-app) mauvaise prise en compte de la librairie imageio qui fait partie des dépendances dans un contexte de déploiement en webapp.
Pour le vérifier, j'ai copié la librairie `jai-imageio-core-1.4.0.jar` dans '/usr/share/tomcat9/lib' et cela résout efffectivement le problème mais ce n'est pas très satisfaisant comme déployer le plugin sur le serveur car cela ne résisterait pas aux maj de la dépendance dans l'application.

Le lien recommande l'utilisation `com.twelvemonkeys.servlet.image.IIOProviderContextListener` pour l'intégrer comme dépendance de l'application. Qu'en pensez-vous ?

Merci par avance.

```
[2021-01-20 12:33:47] [info] #011at java.base/java.lang.Thread.run(Thread.java:830)
/var/log/tomcat9/catalina.out.1-[2021-01-20 12:34:09] [info] 2021-01-20 12:34:09.083  INFO 27416 --- [io-8080-exec-11] o.e.esupsignature.service.UserService    : controle de l'utilisateur fbordina
[2021-01-20 12:34:09] [info] 2021-01-20 12:34:09.177  INFO 27416 --- [io-8080-exec-11] o.e.esupsignature.service.UserService    : mise à jour de l'utilisateur XXX
2021-01-20 12:34:43] [info] 2021-01-20 12:34:43.863 ERROR 27416 --- [io-8080-exec-15] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/user/users] due to exception [com/github/jaiimageio/stream/RawImageInputStream]
/var/log/tomcat9/catalina.out.1:[2021-01-20 12:34:43] [info] java.lang.NoClassDefFoundError: com/github/jaiimageio/stream/RawImageInputStream
[...]
```

**Comment by dlemaignent** [comment]
Bonjour,
J'ai déjà eu le problème avec cette librairie. Cela ne se pose que lorsque que l'on déploie dans tomcat sans redémarrer. Je vais voir si je peux utiliser IIOProviderContextListener, mais en attendant pouvez-vous me confirmer que le redémarrage corrige le problème.
Merci d'avance.

**Comment by cleneveu** [comment]
Bonjour,
Même souci et je confirme que redémarrer tomcat règle le problème.
Clément
