### ISSUE TITLE
Validation de saisie de formulaire inopérante

### ISSUE THREAD

**Issue by hjacob35** [EsupPortail/esup-signature#11]
Bonjour, 
depuis l'installation de la v1.7 , le bouton "Enregistrer les modifications" sur un formulaire n'a plus d'effet  ...

![image](https://user-images.githubusercontent.com/11576603/107622006-73760100-6c57-11eb-9dac-e290d6f75805.png)
![image](https://user-images.githubusercontent.com/11576603/107622047-8be61b80-6c57-11eb-8d81-73371b1c88e9.png)

Henri

**Comment by dlemaignent** [comment]
Bonjour,
Je pense que le problème est corrigé dans la version 1.8. Si possible ça bien de tenter la mise à jour qui devrait être simple. Attention aussi au cache javascript. 
Merci d'avance pour le retour.

**Comment by hjacob35** [comment]
Je clos, c'est corrigé.
Henri
