### ISSUE TITLE
V1.14.4 - le renommage des documents dans un circuit n'est pas fonctionnel (naming-template)

### ISSUE THREAD

**Issue by Fabien-Rocher** [EsupPortail/esup-signature#114]
En V1.14.4 - si je met le pattern **[title][date-fr][user.initiales]** dans le champ "Modèle de nommage" de mon circuit, mon document nommé DOC1 est renommé DOC1_signé.pdf après signature. Cela ne correspond pas au pattern spécifié.

Je n'ai pas testé au niveau du paramètre naming-template: "[user.initials]-[title]" du fichier application.yml mais je penses que les 2 sont liés ? A tester aussi donc.

lié à #88

**Comment by dlemaignent** [comment]
a priori cela fonctionne en 1.14.6
