### ISSUE TITLE
V1.14.4 - Mode brouillon non fonctionnel 

### ISSUE THREAD

**Issue by Fabien-Rocher** [EsupPortail/esup-signature#116]
En V1.14.4 - j'ai testé le fonctionnement du mode brouillon mais je ne vois pas son utilité, ni ne comprend son fonctionnement.
En cliquant sur le + dans le mode brouillon, je peux créer une demande mais à aucun moment il m'est proposé un bouton enregistrer en brouillon. Il ne me semble pas non plus qu'un enregistrement automatique soit en place.
Du coup, où est l'utilité d'un tel mode ?

**Comment by dlemaignent** [comment]
A priori il n'y a pas de mode brouillon dans esup-signature. Dans le tableau de bord il y a un filtre brouillon car ce statut est possible dans le cas où une demande n'aurait pas été envoyée directement lors de ça création.
