### ISSUE TITLE
Impossibilté de modifier les paramètres d'un circuit

### ISSUE THREAD

**Issue by cleneveu** [EsupPortail/esup-signature#12]
Bonjour,

Étant admin, mais pas créateur du circuit, je ne peux pas modifier les paramètres d'un circuit de validation pré-enregistré (ex: **Visa du responsable puis signature de la présidence**), le bouton avec la disquette verte n'apparaît pas.
Dans le code je vois la condition suivante (jamais satisfaite dans mon cas) : 
`${workflow.fromCode == null || !workflow.fromCode}`

Je précise que nous sommes en version 1.8

**Petite question subsidiaire** : y'a-t-il un moyen de dupliquer un circuit de validation dans l'interface d'administration ? Si non est-ce une évolution envisagée ou envisageable.

Bien cordialement

Clément

**Comment by dlemaignent** [comment]
Bonjour,
Cela est normal, ces circuits sont issus des classes "workflow" donc non modifiables via l'interface graphique voir : 
https://www.esup-portail.org/wiki/display/SIGN/Documentation+administrateur#Documentationadministrateur-Cr%C3%A9eruneclasseworkflow
Pour l'instant pas de possibilité de dupliquer un workflow, on note l'idée.
Bien cordialement,
