### ISSUE TITLE
V1.14.4 - Signature Calligraphique impossible sur un fichier qui revendique la conformité à la norme PDF/A

### ISSUE THREAD

**Issue by Fabien-Rocher** [EsupPortail/esup-signature#120]
Notre imprimante réseau génère lors des scans des pdfs à la norme PDF/A, c'est à dire verrouillés pour l'archivage et lorsque nous utilisons ces pdfs au travers d'Esup-signature, le circuit de signature se déroule normalement et aucune erreur n'est affichée.
Cependant au retour sur le document en fin de circuit, la signature a disparu !
En outre, en utilisant un pdf classique (enregistré à partir de Word ou Acrobat Reader), tout est en ordre.
Du coup, il y a un bug avec l'utilisation des fichiers qui revendiquent la norme PDF/A. 
D'après mes tests, le niveau de conformité appliqué sur mon pdf est : PDF/A-1a
Je mets en pièce jointe ce pdf pour test.
[scan_rocher202_2021-08-26-15-55-47.pdf](https://github.com/EsupPortail/esup-signature/files/7060681/scan_rocher202_2021-08-26-15-55-47.pdf)
.

**Comment by dlemaignent** [comment]
Problème corrigé dans la version 1.14.7, les PDF/A seront convertis lors de l'import s'ils ne contiennes pas de signature
