### ISSUE TITLE
Filtre sélection des circuits ne fonctionnent pas (menu Admin)

### ISSUE THREAD

**Issue by cleneveu** [EsupPortail/esup-signature#13]
Bonjour,
Dans le menu Admin > Circuits si choisit autre chose que **Workflows globaux (définis par les utilisateurs)**, ça mouline mais on retombe sur ce même choix. 
Pas de trace ni de message d'erreur, je suis avec la version 1.9-SNAPSHOT.
Bonne journée
Clément

**Comment by dlemaignent** [comment]
C'est corrigé depuis la 1.11.4.
Cdlt
