### ISSUE TITLE
Image de la signature partiellement dupliquée si horodatée

### ISSUE THREAD

**Issue by cleneveu** [EsupPortail/esup-signature#132]
Bonjour,
Pour reproduire le petit bug d'affichage : 
- on créée une auto-signature (reproduit aussi dans le ca d'un circuit de signature)
- on place et horodate la signature
le haut de la signature est partiellement dupliquée (cf. encadré rouge dans l'image)
![Bug_Esup_Signature_horodatage](https://user-images.githubusercontent.com/79695750/132333595-bae00675-acae-451d-9733-23819381be1a.png)
Une fois signé la signature apparaît correctement
Bonne journée
Clémenr

**Comment by dlemaignent** [comment]
Bonjour,
Je n'arrive pas à reproduire le problème. Est-ce sur un navigateur particulier ? Je me demande si ça ne pourrait pas être un problème de cache javascript.
Merci d'avance pour ces précisions

**Comment by cleneveu** [comment]
Pardon David je n'avais pas vu la réponse, en effet sur votre version de démo je ne reproduis pas.
Etrange

**Comment by cleneveu** [comment]
En effet gros mea culpa c'est un merdage de ma part quand j'ai customizé les css pour les mettre à la couleur de l'Ecole.

**Comment by dlemaignent** [comment]
Pas de problème, je cloture donc l'issue
