### ISSUE TITLE
V1.14.6 - Bouton "enregistrer le document signé sous " visible alors que le doc n'est pas signé

### ISSUE THREAD

**Issue by Fabien-Rocher** [EsupPortail/esup-signature#133]
Lors d'une demande de signature le bouton bleu "Enregistrer le document signé sous" apparaît alors que le doc n'est pas signé.
Il faudrait le masquer tant que l'état du doc n'est pas "signé". 
Si ce bouton à vocation à rester pour permettre de télécharger le doc même avant signature, dans ce cas il faudrait revoir son infobulle ;-)
![btn-enregistrer-sous](https://user-images.githubusercontent.com/86477182/132637135-742c5e66-3541-4d27-83db-24f7f9634afc.PNG)

**Comment by dlemaignent** [comment]
Bouton modifier dans la 1.14.7
