### ISSUE TITLE
Placement de signature

### ISSUE THREAD

**Issue by cleneveu** [EsupPortail/esup-signature#14]
Bonjour,
Je n'arrive pas à placer la signature comme je le souhaite. Pour reproduire : 

- Je crée un circuit de validation via **Créer une demande personnalisée**, à ce moment là si je mets un document dedans je peux placer la signature comme je le souhaite, je sors du circuit.
- je réutilise ce circuit avec le même document (ou un différent) je n'ai plus la possibilité de placer la signature où je le souhaite.

Bonne journée

Clément

**Comment by dlemaignent** [comment]
Bonjour,

D'après nos tests la ré-utilisation d'un circuit fonctionne bien. La particularité est qu'il est nécessaire de démarrer manuellement la demande après avoir ajouté un document. Nous pensons modifier cela pour supprimes cette étape.
Bien cordialement,
David

**Comment by cleneveu** [comment]
Bonjour David,
OK c'est noté.
Bonne journée.
Clément
