### ISSUE TITLE
Envoi de mail à la fin d'un circuit de signature

### ISSUE THREAD

**Issue by cleneveu** [EsupPortail/esup-signature#15]
Bonjour,
J'ai un circuit de signature (mode Admin) avec un envoi de mail comme destination de document, cf. pièce ci-après : 
![circuit_signature_avec_envoi_mail](https://user-images.githubusercontent.com/79695750/111479638-7326c500-8731-11eb-9947-313a0636aa81.png) 
Après la signature finale le fonctionnement est étrange : 
- l'adresse de réception n'arrête pas de recevoir des mail sans le document final.
- dans les log je vois ça (trace complète en pièce jointe)
[erreur_esup_signature_envoi_mail.txt](https://github.com/EsupPortail/esup-signature/files/6156929/erreur_esup_signature_envoi_mail.txt)
 : 
```
Caused by: org.postgresql.util.PSQLException: ERREUR: la valeur d'une clé dupliquée rompt la contrainte unique « uk_hqxkfe280g76njopgvx2xv91v »
  Detail: La clé « (viewers_id)=(1043) » existe déjà.
```
La clef **uk_hqxkfe280g76njopgvx2xv91v** étant celle de la table **sign_request_viewers**

Le principal problème est que cet envoi de mail ne s'arrête que si je supprime le document, sinon on est en mode Spam. Ai-je fait quelque chose de moche dans mon paramétrage ?

**Comment by dlemaignent** [comment]
Bonjour,

Oui c'est bien un problème coté esup signature. Ça sera corrigé avec la 1.11 (je viens de mettre en ligne la 1.11-SNAPSHOT sur la branche master), le champ "viewers" à été déplacé. Il faudra supprimer la contrainte sur sign_book_viewers si elle existe et supprimer la table sign_request_viewers si à la main comme suit : 

Dans psql : 

-- connexion à la base esupsignature

\c esupsignature

-- supprimer la contrainte unique sur viewers_id de la table sign_book_viewers

\d sign_book_viewers

-- postgres=# \c esupsignature_test
-- You are now connected to database "esupsignature_test" as user "postgres".
-- esupsignature_test=# \d sign_book_
-- Did not find any relation named "sign_book_".
-- esupsignature_test=# \d sign_book_viewers
--  Table "public.sign_book_viewers"
--     Column    |  Type  | Modifiers
-- --------------+--------+-----------
--  sign_book_id | bigint | not null
--  viewers_id   | bigint | not null
-- Indexes:
--     "**uk_gt3duxi8s9hmjyrakbjrwlhpk**" UNIQUE CONSTRAINT, btree (viewers_id)
-- Foreign-key constraints:
--     "fkbba225ae2q2t0ncl2cihttsh6" FOREIGN KEY (sign_book_id) REFERENCES sign_book(id)
--     "fkecvisojhprwbqypbx5ec8q2jf" FOREIGN KEY (viewers_id) REFERENCES user_account(id)

--on supprime la contrainte ainsi :

alter table sign_book_viewers drop constraint if exists **uk_gt3duxi8s9hmjyrakbjrwlhpk**;

drop table if exists sign_request_viewers;

**Comment by cleneveu** [comment]
Super merci.
Clément
