### ISSUE TITLE
Nullpointer ajout emplacement signature

### ISSUE THREAD

**Issue by piougy** [EsupPortail/esup-signature#163]
Lors de l'ajout de l'emplacement d'une signature sur le processus "Créer une demande de signature" on obtient un nullpointer

Dans le fichier SignRequestService.java ligne 1243 remplacer

		commentService.create(id, commentText, commentPosX, commentPosY, commentPageNumber, spotStepNumber, postit.equals("on"), null, authUserEppn);

par

		commentService.create(id, commentText, commentPosX, commentPosY, commentPageNumber, spotStepNumber, "on".equals(postit), null, authUserEppn);

**Comment by dlemaignent** [comment]
En effet il y a un problème, l'attribut ready n'est plus utilisé. Il faut donc que je corrige la fonction check. Mais le cas ne doit se présenté que lorsqu'il y a plusieurs signatures à la même étape je pense.
