### ISSUE TITLE
V1.15 l'utilisateur système "creator" n'est plus accessible

### ISSUE THREAD

**Issue by fredfr94** [EsupPortail/esup-signature#165]
"CREATOR" n'est plus disponible dans la nouvelle version 1.15. J'obtiens ce message:
`Aucun résultat. Pour ajouter une personne externe entrer une adresse email`
- testé en local
- testé sur [demo.univ-rouen](https://esup-signature-demo.univ-rouen.fr/user/)

Le participant "CREATOR" me permet de créer des circuits génériques. L'initiateur de mon circuit peut ainsi remplir lui même le formulaire qu'il décide ensuite de faire signer.

Voici ce qui s'affichait dans l'ancienne version (chez moi 1.13.2):
![image](https://user-images.githubusercontent.com/74240298/138900220-b13448bf-705c-4342-847c-9819ff17b13c.png)

"CREATOR" n'est pas indiqué dans la documentation. C'est pourtant un élément essentiel dans la conception de circuits génériques. Existe t'il une nouvelle façon de faire qui m'aurait échappée ?

Merci,

Frédéric Loze * DSI upec

**Comment by dlemaignent** [comment]
Oui en effet le problème sera corrigé dans la toute prochaine version 1.15.4
