### ISSUE TITLE
Page blanche lorsque j'essaie d'éditer le certificat de signature

### ISSUE THREAD

**Issue by cleneveu** [EsupPortail/esup-signature#171]
En version chez nous (1.15.3-SNAPSHOT) et sur la plateforme de démo
Pour reproduire : 

1. je signe un document (peu importe le mode opératoire, une auto signature suffit)
2. je télécharge le document signé
3. je clique sur la signature ou je copie de lien et essaie d'ouvrir la page du lien vers le certificat avec un navigateur avec lequel je ne suis pas connecté sur signature

J'obtiens alors une page blanche, ce qui signifie qu'une personne extérieure à l'établissement n'a pas accès au certificat de signature.
J vous joint un doc signe sur la plateforme de démo  (lien vers le certificat de signature : https://esup-signature-demo.univ-rouen.fr/public/control/6949682504757300966, le pdf signé : [Appel_de_Fond_10-12-2021_signé.pdf](https://github.com/EsupPortail/esup-signature/files/7512074/Appel_de_Fond_10-12-2021_signe.pdf))

Comme je reproduis en local sur mon ordinateur j'ajoute aussi la trace [trace_erreur_page_blanche.txt](https://github.com/EsupPortail/esup-signature/files/7512667/trace_erreur_page_blanche.txt)

**Comment by cleneveu** [comment]
Visiblement c'est un problème avec Spring Security, dans la classe *WebSecurityConfig.java*, ça fonctionne correctement lorsque je rajoute dans la méthode **configure** le code suivant : 
```java
		http.logout()
				.logoutRequestMatcher(
						new AntPathRequestMatcher("/logout")
				)
				.addLogoutHandler(logoutHandler())
				.logoutSuccessUrl("/login").permitAll()
// ligne rajouté après le permitAll
				.and().csrf().csrfTokenRepository(new HttpSessionCsrfTokenRepository());
```

cf. https://html.developreference.com/article/11216886/Spring+security+%3A+logout+not+working+if+button+is+pressed+after+the+session+is+expired et https://www.programcreek.com/java-api-examples/?code=nicodewet%2Ftemplate-spring-boot-oauth2-wso2-is%2Ftemplate-spring-boot-oauth2-wso2-is-master%2Fsrc%2Fmain%2Fjava%2Fhello%2FApp.java

**Comment by dlemaignent** [comment]
Merci pour la remonté du problème. A force de testé en mode connecté, je n'ai pas remarqué que des attributs étaient manquant pour le utilisateurs en mode anonyme. Je corrige ça dans la futur 1.15.4
