### ISSUE TITLE
V1.15.1 déactiver nom et filigrane par défaut

### ISSUE THREAD

**Issue by dsiieptoul** [EsupPortail/esup-signature#174]
Bonjour,

Suite à une montée de version en 1.15.1 quand on signe un document un filigrane, le nom du signataire et la date sont automatiquement ajoutés à la signature. On peut tout de même les enlever, mais comment revenir au comportement antérieur ? ( ne pas les avoir par défaut).

Merci pour cette application.

**Comment by dlemaignent** [comment]
Bonjour,

Je vais prochainement corriger le comportement de cette partie que devra mémoriser les paramètres de la dernière signature de l'utilisateur
