### ISSUE TITLE
Question sur les signatures et visas

### ISSUE THREAD

**Issue by cleneveu** [EsupPortail/esup-signature#23]
Bonjour,

Y'a-t-il moyen d’apposer une signature (ou un visa) sur chaque page d'un document sans passer par une étape par feuille (ce qui pourrait s'avérer très long pour certains documents). Cela s’apparenterait à un paraphe en bas de chaque page.

Si ce n'est pas possible est-ce une demande d'évolution envisageable ?

Bonne journée

Clément

**Comment by dlemaignent** [comment]
Bonjour, 
Normalement il est déjà possible d'ajouter n signatures lors d'une même étape à l'aide du bouton "Ajouter une signature" dans la barre d'outils.
Cdlt

**Comment by cleneveu** [comment]
Re-bonjour,
Je suis d'accord, mais on ne peut le faire que sur une seule page. Mais la demande que l'on m'a soumise serait de pouvoir rajouter un paraphe en bas de toutes les pages d'un pdf. Un peu comme lorsque l'on signe un contrat ou un devis par exemple.
Cordialement

**Comment by dlemaignent** [comment]
Sauf bug, les signatures peuvent être mises sur toutes les pages. Lorsqu'une signature est sélectionnée, elle suit lors des changements de page. Il est possible d'enregistrer un paraphe au niveau des paramètres de signature puis d'en déposer un sur chaque page.

**Comment by cleneveu** [comment]
Ah oui, grand merci je n'avais pas vu que c'était possible... 
Juste une remarque avant de clore le sujet. Lors de ce cas d'usage (que je viens de tester avec succès), lorsque le demandeur  place la signature (en bas de page par exemple, comme pour un paraphe), ce placement de signature n'est appliqué (côté signataire) que sur la première page du document. Pour les pages suivantes, le signataire doit placer les signatures lui-mêmes. Je ne sais pas si c'est normal, je vous fait juste la remarque, car je ne m'y attendais pas.
