### ISSUE TITLE
[1.31.2] Externes sans SMS

### ISSUE THREAD

**Issue by Orchal** [EsupPortail/esup-signature#467]
**Numéro de version**
1.31.3

**Description du bug**
Bonjour, dès qu'on tape une adresse email, la vérification du champ à chaque caractère tapé provoque l'erreur suivante :

`ERROR 10289 system [0.1-8009-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot invoke "String.length()" because "pattern" is null] with root cause`

Par ailleurs, alors que sms-required est à false, le message suivant apparaît alors :

`Le destinataire saisi n’est pas conforme`
`Soit les destinataires externes ne sont pas autorisés, soit il s’agit d’un groupe vide`

Je suppose qu'il y a quelque chose que je configure mal pour permettre les utilisateurs externes sans pour autant nécessiter un OTP avec SMS.

**Comment le reproduire**
C'est systématique a priori.

Par ailleurs, je tiens à vous féliciter pour cette excellente application !

Merci !

**Comment by dlemaignent** [comment]
Bonjour,
Merci pour le retour et merci pour les encouragements. 
Le log n'est pas complet donc je ne sais pas de quelle fonction cela vient, je n'ai pas de ligne contenant "pattern.length()" dans le code. Y a t'il le reste de la stacktrace dans les logs ?

**Comment by Orchal** [comment]
Bonjour,

en fait pas vraiment il n'y a que ça. Après l'erreur n'est peut-être pas pertinente, et n'a potentiellement aucun lien avec le fait de ne pas pouvoir utiliser d'email externe.
En gros pour moi il s'agît d'une vérification du champ "Choisir les participants", peut-être même côté front du coup, puisque ça intervient à chaque fois que je tape un caractère.

**Comment by Orchal** [comment]
En fait je n'ai rien dans les logs de l'application, cette erreur remonte dans syslog (plutôt côté tomcat je suppose)

**Comment by Orchal** [comment]
Désolé, j'ai reset la DB et il n'y a plus aucun soucis. Je suppose que j'ai fait une mauvaise mise à jour à un moment donné ou un autre...
