### ISSUE TITLE
[1.31.4] /ws/workflows/XXX/new retourne "recipients must not be empty"

### ISSUE THREAD

**Issue by gawel** [EsupPortail/esup-signature#473]
**Numéro de version**
1.31.4

**Description du bug**
Lorsqu'on appelle le endpoint /ws/workflows/XXX/new l'appli raise "recipients must not be empty"

Deux problèmes ici:

- Dans swagger le champs recipientsEmails est marqué déprécié mais quand on y mets une valeur on obtient aussi "recipients must not be empty"

- Rien n'indique l'obligation de spécifier des recipients (pas de champs obligatoire)

J'imagine que c'est en partie dûe à l'aspect transitoire de ces paramètres. Mais, en attendant, le problème est bien là.

**Comment le reproduire**
curl /ws/workflows/$XXX/new?createByEppn=$eppn + multipart file en POST

**Comment by dlemaignent** [comment]
Bonjour,
En effet la situation est particulière, pour maintenir une rétro-compatibilité le recipientsEmails reste fonctionnel. Il faut donc soit le remplir, soit remplir la liste des recipients via le paramètre stepsJsonString. Cela dit, aucun de ces deux champs n'est obligatoire car les destinataires peuvent très bien être pré-renseignés au niveau des circuits, directement. "recipients must not be empty' ne devrait apparaitre que s'il n'y a pas de destinataire ni dans le circuit, ni dans l'un ou l'autre des paramètres

**Comment by gawel** [comment]
Bonjour, et merci pour votre réactivité.

J'avoue que votre réponse me surprends. J'ai bien tenté `&recipientsEmails=XXX` mais sans succès. On obtient aussi l’erreur décrite.

Etant simple consommateur de l'api je ne sais trop dire si c'est du à la configuration du parcours ou une vrai erreur.

**Comment by dlemaignent** [comment]
Bonjour,
Chez moi ça fonctionne avec cette requête :
`curl -L -X POST 'http://esup-signature.univ-ville.fr/ws/workflows/xxxxx/new' \
-H 'X-API-Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
-F 'createByEppn="system"' \
-F 'recipientsEmails="1*a@univ-ville.fr*1,2*b@univ-rouen.fr"' \
-F 'multipartFiles=@"/tmp/sample.pdf"''`

et cette configuration de circuit
![image](https://github.com/user-attachments/assets/c3dc2146-ff4c-411f-936b-05de175689ec)

Même fonctionnement avec une seule étape. Pour moi le seul moyen de reproduire le problème est d'avoir un circuit vide et de ne pas transmettre de destinataires. (X-API-Key est facultatif, cela dépend de l'activation, ou non, des tokens)

**Comment by gawel** [comment]
Bonjour,

Nous avons pu avancer en indiquant les signataires au niveau du circuit. (toujours impossible via l'url, hélas)

Nous n'allons pas creuser plus. Nous ferons le nécessaire pour supporter les nouveaux paramètres à court/moyen terme.

Encore merci pour votre réactivité et ces précieuses indications qui nous ont débloquées.

Je ferme ce ticket
