### ISSUE TITLE
Champ multiligne dans un formulaire ne fonctionne plus

### ISSUE THREAD

**Issue by dsiieptoul** [EsupPortail/esup-signature#7]
Bonjour,

Suite à la maj 1.4

 les champs multi-ligne d'un formulaire PDF ne fonctionnent plus. On obtient systématiquement une alerte javascript : "Un champ n'est pas rempli en page 1"

Les champs multi-lignes fonctionnaient en version 1.3

Dans l'exemple ci-dessous vous pouvez constater que le champ adresseDomicile n'est pas correctement traité par jquery

![image](https://user-images.githubusercontent.com/77722932/105152707-d0bedc80-5b07-11eb-9b5b-7bfa8b8f4add.png)

**Comment by dlemaignent** [comment]
Bonjour,
Comme indiqué dans le changelog (https://www.esup-portail.org/wiki/display/SIGN/Change+log#Changelog-v1.5-SNAPSHOT-18/07/2020) le problème est sensé être corrigé depuis la version 1.5. Si possible merci de passer au moins à cette version et de me confirmer que ça corrige bien le problème.
Cordialement.

**Comment by dsiieptoul** [comment]
Bonjour,

Merci de votre retour mais le problème n'est pas réglé : Le contenu du champ multi-ligne est effacé après l'enregistrement de la demande.

Les champs en ligne simple fonctionnent.

Cordialement,

**Comment by dlemaignent** [comment]
Bonjour,
En effet j'arrive bien à reproduire le problème. Je regarde ça et reviens vers vous.
Cordialement,
David
