### ISSUE TITLE
Erreur validation formulaire champs requis et étape de validation

### ISSUE THREAD

**Issue by dsiieptoul** [EsupPortail/esup-signature#8]
Bonjour,

Dans un formulaire, si l'on a un champ "requis" à une étape > 0 alors on obtient systématiquement une alerte javascript : "Un champ n'est pas rempli en page 1" lors de la tentative d'enregistrement à l'étape 0.

Version 1.4 snapshot 

Cordialement,

**Comment by dlemaignent** [comment]
Je fusionne avec l'issue #7 car les problèmes sont liés
