### ISSUE TITLE
Visa visuel en v1.14.3

### ISSUE THREAD

**Issue by Fabien-Rocher** [EsupPortail/esup-signature#87]
Plusieurs problèmes soulevés sur le visa visuel : 

1/ le type de signature est nommée signature calligraphique alors qu'il s'agit d'un visa visuel. 
De plus l'info-bulle au passage sur bouton "TYPE" affiche "Ajouter le nom" au lieu de "Ajouter le type".

2/ les boutons de sélection des signatures calligraphiques (flèches haut et bas) ne servent à rien dans le cas du visa, et provoquent des résultats inattendus si on les utilise (déplacement de la box en pointillée du visa). Il serait préférable de les masquer pour le visa est de les rendre visibles dans les autres cas.

3/ Redimensionnement anarchique lors de l'utilisation du bouton texte au dessus/à droite

4/ Problème de redimensionnement/cadrage du filigrane dans la box après signature

5/ Passage du mode de sélection des éléments à afficher dans le visa (Type, Nom, Date, Texte) aux propriétés du visa (texte au dessus/droite, filigrane, etc.) difficile à comprendre au début, il faut cliquer sur la toute petite zone de sélection de redimensionnement de la box. Est-ce possible d'avoir un bouton de bascule à la place ? Par exemple après la liste déroulante de sélection des couleurs de texte ?

**Comment by dlemaignent** [comment]
L'interface a été améliorée dans la v1.14.6
