### ISSUE TITLE
Renommage des document en V1.14.3

### ISSUE THREAD

**Issue by Fabien-Rocher** [EsupPortail/esup-signature#88]
Lors de la constitution d'une demande signature dans le cadre d'un circuit, le ou les documents sont tous renommés du nom du circuit utilisé.  
Par exemple : 
Le document nommé "Acte-dengagement-Eiffage-Energie.pdf" devient "Bon de commande DSI_signé.pdf"

Je ne sais pas si c'est un fonctionnement souhaité, mais pour nous c'est très problématique car on perd la nomenclature du fichier d'origine qui indique le type de doc, le service, etc.

Ce fonctionnement n'est constaté dans le cadre des circuits de signature mais pas dans l'auto-signature ou demander une signature.

**Comment by dlemaignent** [comment]
un nouveau système de renommage des fichiers à fait son apparition dans la v1.14.3. On peut configurer un template au niveau global ou au niveau des circuits. Il fonctionne comme suit : 
Le modèle est construit à l'aide d'attributs entre crochets.
default : [title]
Les attributs disponibles sont :
﻿[title] : titre du document original
[id] : identifiant du parapheur
[worflowName] : nom du circuit
[user.name] : nom prénom de l'utilisateur courant
[user.eppn] : eppn de l'utilisateur courant
[user.initials] : initiales de l'utilisateur courant
[UUID] : un identifiant unique
[order] : le numéro d'ordre de création pour un même circuit
[timestamp] : timestamp sous forme de long
[date-fr] : date dd/MM/yyyy hh:mm
[date-en] : date yyyy-MM-dd hh:mm

Normalement sur un circuit donné, en mettant [title] comme template, le nom ne devrait pas changer.

**Comment by Fabien-Rocher** [comment]
Good to know ;-)
Je vais construire mes modèles du coup.
Merci pour l'info !
