### ISSUE TITLE
Changelog : script SQL à passer avant la maj 1.3.1 ?

### ISSUE THREAD

**Issue by fbordina** [EsupPortail/esup-signature#9]
Bonjour,

dans le [changelog](https://www.esup-portail.org/wiki/display/SIGN/Change+lo) de la version 1.3.1, il est demandé de passer un script sql avant de construire l'application. le script indiqué est `update_1.3.1.sql ` de la branche master (pas 1.3.X) alors que le lien sous jacent pointe vers le script `update_1.3_clean.sql` aussi sur la branche master.

Pourriez-vous, svp, corriger le lien avec le bon script à passer avant de construire cette version ?

Merci.

**Comment by dlemaignent** [comment]
Bonjour,

Merci pour l'info, je viens de corriger la documentation.
