### ISSUE TITLE
V1.14.3 Zoom/dézoom du filigranne et de l'horodatage

### ISSUE THREAD

**Issue by Fabien-Rocher** [EsupPortail/esup-signature#90]
Dans la v 1.14.3, lorsque l'on fait un visa visuel, le fait de faire un zoom de celui-ci en tirant le coin en bas à droite provoque un dépassement du texte du visa (le texte est invisible en partie) et un mauvais dimensionnement du filigrane de fond de box (filigrane coupé sur les bords).
Lorsque l'on ne touche pas au coin et au redimensionnement tout est correct.

**Comment by dlemaignent** [comment]
#87
