### ISSUE TITLE
V1.14.3 - Accès observateur interdit

### ISSUE THREAD

**Issue by Fabien-Rocher** [EsupPortail/esup-signature#91]
Lorsque l'on est observateur sur une demande, à la finalisation de la signature une notification est envoyée à tous les participants et aussi aux observateurs, mais l'accès est interdit pour ces derniers.

**Comment by Fabien-Rocher** [comment]
Après des tests en V1.14.4, c'est réparé !

**Comment by Fabien-Rocher** [comment]
Je suis allé vite en besogne, le bug est toujours présent même en V1.14.4.
Je ré-ouvre le ticket.

**Comment by Fabien-Rocher** [comment]
Je précise qu'on est bloqué uniquement quand la demande est terminée, mais tout pendant qu'elle est en cours on a accès en visualisation.
C'est dommage de couper l'accès une fois terminé. Le rôle d'observateur est vraiment éphémère et si on a louper la fenêtre de signature, il n'y a plus rien à observer. Frustrant !

**Comment by dlemaignent** [comment]
Sur la 1.14.6 la demande reste accessible même terminée
